### ISSUE TITLE
Future code reviewing

### ISSUE THREAD

**Issue by Karyum** [JWLD/soundtracks#9]
well im going to keep an eye on your project so you might as well add me as a contributor so i can make labels (dont worry i wont play with the code or push to master im not an asshole)

**Comment by mattlub** [comment]
@Karyum mario if you want to contribute you can fork the repo and submit pull requests

**Comment by Karyum** [comment]
what if i want to make labels and help jack make a todo list for the project ??
and nice [github photo](https://avatars1.githubusercontent.com/u/16781318?v=3&s=400)

**Comment by mattlub** [comment]
@Karyum hmm yeh I'm not sure. You could make an issue requesting the creation of some new labels?

And thanks (but I was slightly worried what that link was gonna contain)

**Comment by Karyum** [comment]
@mattlub but i cant even assign or choose a label for a certain issue. i dont want to keep telling jack to make labels and label a certain issue.
but its fine i might forget about this project because of my amazing memory :stuck_out_tongue_winking_eye:  [and why are you so afraid to open this link?](http://stuffpoint.com/cats/image/205893-cats-cutiee-cat.jpg)
